### ISSUE TITLE
Unable to upgrade projects with transitive dependency to Bumblebee beta

### ISSUE THREAD

**Issue by ccarmannt** [Bumblebee/Bumblebee#124] opened 2018-07-17 13:04 UTC
We have a class library that was using the 2.0.8-beta version of Bumblebee. We recently upgraded it to use the 2.1.0-beta version.

Our downstream projects that depend on this class library cannot be upgraded successfully to the new version. When the attempt is made, the existing reference to Bumblebee is destroyed and no new one is created.

Todd is aware of this issue. We are logging it for tracking purposes. We can provide any additional information as needed.

**Comment by toddmeinershagen** [comment] 2018-07-17 13:36
@ccarmannt - Would you please send me the solution (zipped up) so that I can reproduce the issue and try to figure out what is the root cause?

**Comment by ccarmannt** [comment] 2018-07-17 13:40
I sent it to your meinershagen.net address. Did you not receive it? I can send it again…


Ron Carman, Automation Developer ⁞ 
 nThrive
*****Attention*****
This electronic transmission may contain confidential, sensitive, proprietary and/or privileged information belonging to nThrive, Inc. and its affiliates. In addition, it may also contain patient health information, which may be subject to protection under federal and state privacy laws, including but not limited to the Health Insurance Portability and Accountability Act of 1996, as amended (HIPAA). Authorized recipients of this information are prohibited from disclosing the information to any unauthorized party and are required to properly dispose of the information upon fulfillment of its need and/or use, unless otherwise required by law. Access to this transmission (including any attachments) by anyone other than the intended recipient is not authorized. If you are not the intended recipient, you are notified that any use, dissemination, distribution, printing  or copying of this transmission is strictly prohibited and may subject you to criminal or civil penalties. If you have received this transmission in error, please notify the sender and immediately delete this message from your computer.

**Comment by toddmeinershagen** [comment] 2019-03-28 02:12
@ccarmannt As we discussed, this had to do with the pre-release versioning of v2.  This is now fully released as a GA version, so you should be able to move past this obstacle at this point.  I will close for now.

**Closed by toddmeinershagen** 2019-03-28 02:12 UTC
Labels: question
